### ISSUE TITLE
errors to obtaing the Device Tree with Xiaomi Firmwares

### ISSUE THREAD

**Issue by bm0x** [SebaUbuntu/aospdtgen#14]
Android device tree generator
Version 0.1.0

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bm0x/aospdtgen/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/bm0x/aospdtgen/aospdtgen/main.py", line 30, in main
    dump = DeviceTree(args.dump_path)
  File "/home/bm0x/aospdtgen/aospdtgen/devicetree.py", line 31, in __init__
    self.all_files = [file for file in self.all_files_txt.open().read().splitlines()
  File "/usr/local/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
NotADirectoryError: [Errno 20] Not a directory: 'nabu_dpp_android_images_2.05.07.native.user.dpp_20220507.0000.00_13.0_4a3b03edc2.tgz/all_files.txt'

**Comment by bm0x** [comment]
literally not obtain the all_files.txt

but the firmware not have that file...

any posible alt way to use the tool?

**Comment by SebaUbuntu** [comment]
You just needed to read the README...
