### ISSUE TITLE
Failure during generating X6C6F device tree

### ISSUE THREAD

**Issue by 00p513-dev** [SebaUbuntu/aospdtgen#15]
Dump link: https://dumps.tadiphone.dev/dumps/lenovo/x6c6f

Git commit: [14cb0d6](https://github.com/SebaUbuntu/aospdtgen/commit/14cb0d6ced506dc6460c3bcff2c259023f2232f9)

```
[amy@daisy rom]$ python3 -m aospdtgen /home/amy/Downloads/x6c6f-full_P98928JA1-user-11-RP1A.200720.011-tb8766p164bspP3-release-keys/
Android device tree generator
Version 0.1.0

[2022-05-31 21:07:44,381] [manifest.py:76 WARNING] import_file: Unknown HAL type native
[2022-05-31 21:07:44,513] [__init__.py:104 INFO] __init__: Cloning AIK...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/amy/.local/lib/python3.10/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/amy/.local/lib/python3.10/site-packages/aospdtgen/main.py", line 31, in main
    dump.dump_to_folder(args.output)
  File "/home/amy/.local/lib/python3.10/site-packages/aospdtgen/devicetree.py", line 123, in dump_to_folder
    (folder / f"{partition.model.name}.prop").write_text(partition.build_prop.get_readable_list(IGNORED_PROPS))
  File "/usr/lib/python3.10/pathlib.py", line 1153, in write_text
    return f.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 758: ordinal not in range(128)
[amy@daisy rom]$
```

**Comment by 00p513-dev** [comment]
Just tested now and works great thank you :)
